version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: my_db
    environment:
      MYSQL_ROOT_PASSWORD: pwd
      MYSQL_DATABASE: my-db
      MYSQL_USER: admin
      MYSQL_PASSWORD: pwd
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - "mynet"
  my-golang-app:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - "mynet"
    restart: on-failure
  redis:
    image: redis:latest
    environment:
      REDIS_PASSWORD: pwd
    ports:
      - "6379:6379"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      - "mynet"
networks:
  mynet:
    driver: "bridge"
